version: "3.9"

services:
  db:
    image: my_mysql
    volumes:
      - db_vol:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -p0000
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure

  web:
    image: my_django
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl -f localhost:8000
      interval: 5m
      timeout: 5s
      retries: 3
    restart: on-failure

volumes:
  db_vol:
